language: node_js
cache:
  directories:
    - ~/.npm
    - "node_modules"
notifications:
  email: false
node_js:
  - '9'
script:
  - "npm run test"
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
before_deploy:
  - "npm run webpack"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
