language: node_js
before_script:
  - "npm install --global typescript"
script:
  - commitlint-travis
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: master