language: node_js
node_js:
  - "9"
before_script:
  - git remote add origin https://${GITHUB_TOKEN}@github.com/lokesh-coder/travis-learn-and-practice.git
  - "npm install --global typescript"
script:
  - "npm run test"
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run release
before_deploy:
  - "npm run webpack"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  directories:
  - node_modules
branches:
  only:
    - master